import sys
Import('env')
Import('debug')

env = env.Copy()
env.Append(CPPPATH=['..', '.'])
env.Append(LIBPATH=['../mrt'])
env.Append(CPPDEFINES=['SDLXAPI=DLLEXPORT'])

libs = ['mrt', 'SDL', 'SDL_image', 'SDL_ttf']

if sys.platform != "win32":
	c_map = env.SharedObject('c_map.cpp', CXXFLAGS=['-fforce-addr', '-fprefetch-loop-arrays'])
	libs.append('GL')
else: 
	c_map = env.SharedObject('c_map.cpp')
	libs.append('opengl32')
	libs.append('winmm')
	libs.append('user32')

sdlx_sources = 	['cursor.cpp', 'sdl_ex.cpp', 'surface.cpp', 'system.cpp', 'joystick.cpp', 'ttf.cpp', 
	'thread.cpp', 'mutex.cpp', 'semaphore.cpp',
	'glSDL/glSDL.c', c_map, 'font.cpp', 'timer.cpp', 
	]

sdlx = env.SharedLibrary('sdlx', sdlx_sources, LIBS=libs)
Install('#', sdlx)
