import sys
Import('env')

env = env.Copy()
env.Append(CPPDEFINES=['MRTAPI=DLLEXPORT'])

libs = ['expat', 'z']

if sys.platform == "win32":
	libs.append('Ws2_32')

mrt = env.SharedLibrary('mrt', \
	['exception.cpp', 'fmt.cpp', 'ioexception.cpp', 'logger.cpp', 'chunk.cpp', 'random.cpp', \
	'file.cpp', 'xml.cpp', 'b64.cpp', 'gzip.cpp', 'serializator.cpp', 'serializable.cpp', 
	'sys_socket.cpp', 'tcp_socket.cpp', 'socket_set.cpp', 'directory.cpp', 'fs_node.cpp', 
	'timespy.cpp', 'crash.cpp', 'locale.cpp', 
	], LIBS=libs)
Install('#', mrt)
