import sys
Import('env')

env = env.Copy()

libs = ['z', 'mrt', 'sdlx']

if sys.platform != "win32":
	env.Append(CPPDEFINES=['ZZIP_HAVE_STDINT_H'])
	env.Append(CPPDEFINES=['ZZIP_HAVE_ENDIAN_H'])
	env.Append(CPPDEFINES=['_USE_MMAP'])

env.Append(CPPPATH=['zzip'])
env.Append(CPPDEFINES=['ZZIPAPI=DLLEXPORT'])
env.Append(LIBPATH=['../mrt', '../sdlx'])

zzip = env.SharedLibrary('zzip', \
	['dir.c', 'err.c', 'fetch.c', 'file.c', 'info.c', 'plugin.c', 'stat.c', 'write.c', 'zip.c', 
	'mrt_zzip_file.cpp', 'mrt_zzip_dir.cpp', 
	], 
	LIBS=libs)

Install('#', zzip[0])
