import os, sys
Import('env')
Import('debug')
Import('sdl_cflags')
Import('sdl_libs')
Import('lib_dir')

env = env.Copy()
env.Append(CPPPATH=['..', '.'])
env.Append(LIBPATH=['../mrt'])
env.Append(LIBPATH=['.'])
env.Append(CPPDEFINES=['CLUNKAPI=DLLEXPORT'])

if sys.platform != 'win32':
	env.Append(LINKFLAGS=['-Wl,-rpath,'+ lib_dir])
	env.Append(LINKFLAGS=['-Wl,-rpath-link,build/' + env['mode'] + '/mrt'])
	env.Append(LINKFLAGS=['-Wl,-rpath-link,build/' + env['mode'] + '/sdlx'])

env.MergeFlags(sdl_cflags, sdl_libs)

clunk = env.SharedLibrary('clunk', 
	['context.cpp', 'sample.cpp', 'object.cpp', 'source.cpp', 'sdl_ex.cpp'], 
	LIBS=['m', 'SDL', 'mrt'])
Install('#', clunk[0])

test = env.Program('clunk_test', ['test.cpp'], LIBS=['mrt', 'clunk'])
Install('#', test)
