import os, sys
Import('env')
Import('debug')
Import('sdl_cflags')
Import('sdl_libs')

env = env.Copy()
env.Append(CPPPATH=['..', '.'])
env.Append(CPPDEFINES=['CLUNKAPI=DLLEXPORT'])

env.MergeFlags(sdl_cflags, sdl_libs)

clunk = env.SharedLibrary('clunk', ['context.cpp'], LIBS=['SDL'])
Install('#', clunk[0])

