import os, sys
Import('env')
Import('debug')
Import('sdl_cflags')
Import('sdl_libs')

env = env.Copy()
env.Append(CPPPATH=['..', '.'])
env.Append(LIBPATH=['../mrt'])
env.Append(LIBPATH=['.'])
env.Append(CPPDEFINES=['CLUNKAPI=DLLEXPORT'])

env.MergeFlags(sdl_cflags, sdl_libs)

clunk = env.SharedLibrary('clunk', ['context.cpp', 'sample.cpp', 'sdl_ex.cpp'], LIBS=['m', 'SDL', 'mrt'])
Install('#', clunk[0])

test = env.Program('clunk_test', ['test.cpp'], LIBS=['mrt', 'clunk'])
Install('#', test)
