Import('env')

env = env.Copy()
env.Append(CPPPATH=['..', '.', '../src'])
bt_menu = env.StaticLibrary('bt_menu', 
	['menuitem.cpp', 'textitem.cpp', 'mapitem.cpp', 'vehicleitem.cpp', 'menu.cpp', 'box.cpp', ] 
	)

