Import('env')

env = env.Copy()
env.Append(CPPPATH=['..', '.', '../src'])
env.Append(CPPDEFINES='BTNETAPI=DLLEXPORT')
bt_net = env.SharedLibrary('bt_net', 
	['protocol.cpp', 'server.cpp', 'client.cpp', 'connection.cpp', 'monitor.cpp'] 
	)

